export const listOfUnits = [
  { value: 'EA',  label: 'Each' },
  { value: 'LB', label: 'Pounds' },
  { value: 'GM', label: 'Gram' },
  { value: 'MG', label: 'Milligram' },
  { value: 'KG', label: 'Kilogram' },
  { value: 'ML', label: 'Milliliter' },
  { value: 'L', label: 'Liter' },
  { value: 'BOX', label: 'Box' },
  { value: 'CS', label: 'Case' },
  { value: 'PK', label: 'Pack' },
  { value: 'HR', label: 'Hour' },
  { value: 'BT', label: 'Bottle' },
  { value: 'FT', label: 'Feet' },
  { value: 'RL', label: 'Roll' },
  { value: 'GL', label: 'Gallon' },
  { value: 'M', label: 'Thousand' },
  { value: 'DZ', label: 'Dozen' },
  { value: 'U', label: 'Unit' },
  { value: 'UG', label: 'Microgram' },
  { value: 'UI', label: 'Unit Active Ingredient' },
  { value: 'KU', label: 'Kilo Unit' },
  { value: 'MU', label: 'Million Unit' },
  { value: 'Bag', label: 'Bag' },
];

