export const listOfUnits = [
  { value: 'EA',  name: 'Each' },
  { value: 'LB', name: 'Pounds' },
  { value: 'GM', name: 'Gram' },
  { value: 'MG', name: 'Milligram' },
  { value: 'KG', name: 'Kilogram' },
  { value: 'ML', name: 'Milliliter' },
  { value: 'L', name: 'Liter' },
  { value: 'BOX', name: 'Box' },
  { value: 'CS', name: 'Case' },
  { value: 'PK', name: 'Pack' },
  { value: 'HR', name: 'Hour' },
  { value: 'BT', name: 'Bottle' },
  { value: 'FT', name: 'Feet' },
  { value: 'RL', name: 'Roll' },
  { value: 'GL', name: 'Gallon' },
  { value: 'M', name: 'Thousand' },
  { value: 'DZ', name: 'Dozen' },
  { value: 'U', name: 'Unit' },
  { value: 'UG', name: 'Microgram' },
  { value: 'UI', name: 'Unit Active Ingredient' },
  { value: 'KU', name: 'Kilounit' },
  { value: 'MU', name: 'Million Unit' },
  { value: 'Bag', name: 'Bag' },
];

