module.exports = {
    requestor: 'Aqil Thanawala',
    dateCreated: Date.now(),
    shipTo: '22 Executive Park ste 250, Irvine CA 92614',
    vendorEmail: 'jeffy@amazon.com',
    vendorPhone: '949.994.9499',
    requestingEntity: 'New Patriot',
    frieghtCost: 0,
    invoiceTotal: 100.00,
    subtotal: 100.00,
    items: [
        {
             vendorItemNumber: 'TS8GJF740K',
             description: 'USB Drive 8GB',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 3,
             unitPrice: 10,
             unitType: 'ea',
             extPrice: 30,
         },
        {
             vendorItemNumber: 'TS16GJF740K',
             description: 'USB Drive 8GB',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 3,
             unitPrice: 20,
             unitType: 'ea',
             extPrice: 60,
         },
        {
             vendorItemNumber: 'Swag Hat',
             description: 'A swaggy hat',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 1,
             unitPrice: 10,
             unitType: 'ea',
             extPrice: 10,
         },
        {
             vendorItemNumber: 'TS8GJF740K',
             description: 'USB Drive 8GB',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 3,
             unitPrice: 10,
             unitType: 'ea',
             extPrice: 30,
         },
        {
             vendorItemNumber: 'TS16GJF740K',
             description: 'USB Drive 8GB',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 3,
             unitPrice: 20,
             unitType: 'ea',
             extPrice: 60,
         },
        {
             vendorItemNumber: 'Swag Hat',
             description: 'A swaggy hat',
             link: 'https://us.transcend-info.com/Embedded/Products/No-768',
             quantity: 1,
             unitPrice: 10,
             unitType: 'ea',
             extPrice: 10,
         }
    ]
}